//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeltonikaFirmwareUpdateManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TeltonikaFirmwareUpdateManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add IP.
        /// </summary>
        public static string AddIP {
            get {
                return ResourceManager.GetString("AddIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting with SSH to.
        /// </summary>
        public static string ConnectingSSH {
            get {
                return ResourceManager.GetString("ConnectingSSH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Password.
        /// </summary>
        public static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error with IP.
        /// </summary>
        public static string ErrorWithIP {
            get {
                return ResourceManager.GetString("ErrorWithIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished!.
        /// </summary>
        public static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running firmware update on .
        /// </summary>
        public static string FirmwareUpdateStart {
            get {
                return ResourceManager.GetString("FirmwareUpdateStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware upload to .
        /// </summary>
        public static string FirmwareUpload1 {
            get {
                return ResourceManager.GetString("FirmwareUpload1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  done!.
        /// </summary>
        public static string FirmwareUpload2 {
            get {
                return ResourceManager.GetString("FirmwareUpload2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IP is already on the list..
        /// </summary>
        public static string IPAlreadyOnList {
            get {
                return ResourceManager.GetString("IPAlreadyOnList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teltonika Firmware Update Manager.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select at least 1 device..
        /// </summary>
        public static string NoDevicesSelected {
            get {
                return ResourceManager.GetString("NoDevicesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking if password is correct....
        /// </summary>
        public static string PasswordCheck {
            get {
                return ResourceManager.GetString("PasswordCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Password!.
        /// </summary>
        public static string PasswordIncorrect {
            get {
                return ResourceManager.GetString("PasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove IP.
        /// </summary>
        public static string RemoveIP {
            get {
                return ResourceManager.GetString("RemoveIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Modem.
        /// </summary>
        public static string SearchModem {
            get {
                return ResourceManager.GetString("SearchModem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Firmware File.
        /// </summary>
        public static string SelectFirmwareFile {
            get {
                return ResourceManager.GetString("SelectFirmwareFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update All.
        /// </summary>
        public static string UpdateAll {
            get {
                return ResourceManager.GetString("UpdateAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to update.
        /// </summary>
        public static string UpdateConfirmation1 {
            get {
                return ResourceManager.GetString("UpdateConfirmation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to modem? This could take some time..
        /// </summary>
        public static string UpdateConfirmation2 {
            get {
                return ResourceManager.GetString("UpdateConfirmation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update finished! Restarting modem....
        /// </summary>
        public static string UpdateFinishedRestarting {
            get {
                return ResourceManager.GetString("UpdateFinishedRestarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Selected.
        /// </summary>
        public static string UpdateSelected {
            get {
                return ResourceManager.GetString("UpdateSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading firmware with SCP to.
        /// </summary>
        public static string UploadingFirmwareSCP {
            get {
                return ResourceManager.GetString("UploadingFirmwareSCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
